server:
  http_listen_port: 9080
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: local-test
    static_configs:
      - targets: ['localhost']
        labels:
          job: local-test
          __path__: /tmp/*.log
